// input.rs: Configuration file input menu
//
// Copyright (C) 2023 Andrew Rioux
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

use web_sys::HtmlInputElement;
use yew::prelude::*;

#[function_component]
pub fn InitEditor() -> Html {
    let editor_state = use_context::<crate::state::EditorStateContext>().unwrap();

    let input_node_ref = use_node_ref();

    let (editor_box, error) = match &*editor_state {
        crate::state::EditorState::HasConfig {
            ref editor_box,
            ref error,
            ..
        } => (editor_box, error),
        crate::state::EditorState::Initializing {
            ref editor_box,
            ref error,
        } => (editor_box, error),
    };

    let onchange = {
        let input_node_ref = input_node_ref.clone();
        let editor_state = editor_state.clone();

        Callback::from(move |_| {
            if let Some(input) = input_node_ref.cast::<HtmlInputElement>() {
                let value = input.value();

                editor_state.dispatch(crate::state::EditorMessage::UpdateInitialEditor(value));
            }
        })
    };

    let onfinish = {
        let editor_state = editor_state.clone();

        Callback::from(move |_| {
            editor_state.dispatch(crate::state::EditorMessage::FinishInit);
        })
    };

    let oncreatenew = {
        let editor_state = editor_state.clone();

        Callback::from(move |_| {
            editor_state.dispatch(crate::state::EditorMessage::CreateNew);
        })
    };

    html! {
        <main id="input">
            if let Some(msg) = &error {
                <div id="error">{ "Error! " } { msg }</div>
            }

            <h3>{ "Enter the configuration file to edit" }</h3>

            <p>{ "This must be a file that was generated by this program previously" }</p>

            <textarea value={editor_box.clone()} onchange={onchange} ref={input_node_ref} />

            <a href="#" onclick={onfinish}>{ "Load configuration" }</a>
            <a href="#" onclick={oncreatenew}>{ "Create new configuration" }</a>
        </main>
    }
}
